site_name: HyperGraph Isomorphism Checker
site_description: Documentation for the HyperGraph Isomorphism Checker project
site_author: Your Name
repo_url: https://github.com/UCL-ARC/HyperGraph-Isomorphism-Checker
repo_name: HyperGraph-Isomorphism-Checker

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            docstring_style: google
            show_source: true
            show_root_heading: true
            show_root_full_path: false
            heading_level: 2
      enable_inventory: true

nav:
  - Home: index.md
  - Getting Started:
      - Installation: getting-started/installation.md
      - Quick Start: getting-started/quickstart.md
      - Algorithm: getting-started/algorithm.md
  - API Reference:
      - Node: api/node.md
      - HyperEdge: api/hyperedge.md
      - Hypergraph: api/hypergraph.md
      - Draw: api/draw.md
      - Graph Utilities: api/graph_utils.md
      - Signature: api/signature.md
      - Diagram: api/diagram.md
      - Isomorphisms: api/isomorphisms.md
      - Validation: api/validation.md
      - Utilities: api/utilities.md
  - Examples: examples.md
  - Contributing: contributing.md

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - attr_list
  - md_in_html

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
